stages:
   - build

docker-build:
   image: carlonluca/docker-multiarch:dev
   stage: build
   services:
      - docker:dind
   before_script:
      - docker login -u "$CI_DOCKER_HUB_USER" -p "$CI_DOCKER_HUB_PASSWORD" docker.io
   script:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - docker buildx create --use
      #- docker buildx build --platform linux/arm/v6 -t carlonluca/gitea:$VERSION .
      #- docker buildx build --platform linux/arm/v7 -t carlonluca/gitea:$VERSION .
      #- docker buildx build --platform linux/386 -t carlonluca/gitea:$VERSION .
      #- docker buildx build --platform linux/arm64/v8 -t carlonluca/gitea:$VERSION .
      #- docker buildx build --platform linux/amd64 -t carlonluca/gitea:$VERSION .
      - docker buildx build --push --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8 -t carlonluca/gitea:$VERSION .
   rules:
      - when: manual
